### PR TITLE
It 1 edit existing station, delete station from /stations & /stations/:id

### PR DESCRIPTION
**Pull request by ebassity**
feature test for the following:
- edit existing station
- delete station from /stations
- delete station from /stations/:id

quick note: also added a few backlog items for confirmation messages that we can display to users to confirm creation/deletion/edits when they are redirected to /stations (or on the page the action occurs in the case of a reload such as when deleting from the /stations page)

### CODE REVIEW

**Comment by ebassity** [comment]
connects to #17

**Comment by ebassity** [comment]
connects to #13

**Comment by ebassity** [comment]
closes #17

**Comment by ebassity** [comment]
closes #13

**Comment by ebassity** [comment]
@Carmer Are we doing this right? Tagging you in a closed PR b/c we've done several in our project so far, but when we try to do a new one to tag you in, there's "nothing to compare" and hence no way to do a new PR... anyway, please let us know. Thank you!

**Comment by Carmer** [comment]
These tests look really good. Also, good message on this PR. I would suggest using the code review tool in the PR under the files changed tab. Your team can review the work there and can code conversations. The advantage to doing it here rather than in person is that you document the decisions made and anyone stepping into your code base can see the reasons behind decisions. Plus you have a historical record that way.

**Pull request merged**
